version: '3'
services:
  rabbit:
    hostname: rabbit
    image: rabbitmq:3.7-management-alpine
    environment:
      - SERVICE_NAME=rabbit
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS= guest
    ports:
      # forward port for debugging
      - "5672:5672"
      - "15672:15672"
  classes_worker:
    build:
      context: $PWD
      dockerfile: classes.Dockerfile
    volumes:
      - $PWD/scripts/logs:/tdm/logs/
      - $PWD/scripts/data:/tdm/data/
      - $PWD/scripts/conf/config.py:/tdm/scripts/config.py
    depends_on:
      - rabbit
  attendance_worker:
    build:
      context: $PWD
      dockerfile: attendance.Dockerfile
    volumes:
      - $PWD/scripts/logs:/tdm/logs/
      - $PWD/scripts/data:/tdm/data/
      - $PWD/scripts/conf/config.py:/tdm/scripts/config.py
    depends_on:
      - rabbit
  monitor:
    image: mher/flower
    ports:
      - "5555:5555"
    entrypoint: flower
    command:  --port=5555 --broker=amqp://rabbit:5672/
    depends_on:
      - rabbit
  tdm_es:
    user: "${UID}:${GID}"
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.1
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=tdm-dev
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1000m -Xmx1800m"
      - network.host=0.0.0.0
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - $PWD/scripts/data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
volumes:
  data:
